### ISSUE TITLE
插件请求某些接口报错400

### ISSUE THREAD

**Issue by 7x0** [c0ny1/captcha-killer#2]
如request temple：Authorization:APPCODE e9e1e81f024742b4b3a8f57afc6c283
结果：request Raw: Authorization:APPCODE

**Comment by 7x0** [comment]
从repeater里send to captcha-kill 会有格式的变化，😶，一个请求200.一个请求400

**Comment by c0ny1** [comment]
信息太少了，你截个图吧。

**Comment by c0ny1** [comment]
200请求变成400是请求验证码还是请求接口

**Comment by 7x0** [comment]
Repeater：
<img width="998" alt="截屏2019-12-19下午3 38 46" src="https://user-images.githubusercontent.com/45502788/71154223-ff6be300-2275-11ea-8568-498907e496cc.png">

captcha-kill：
<img width="817" alt="截屏2019-12-19下午3 39 01" src="https://user-images.githubusercontent.com/45502788/71154199-f3802100-2275-11ea-921c-6614bcdc5c12.png">

<img width="884" alt="截屏2019-12-19下午3 39 20" src="https://user-images.githubusercontent.com/45502788/71154153-d5b2bc00-2275-11ea-97f2-e33ca33e28eb.png">

同样的请求从repeater发送到captcha-kill，请求结果就变成了这样。如果将captcha-kill中的POST请求方式改成Get，那么就正常：
<img width="835" alt="截屏2019-12-19下午3 42 43" src="https://user-images.githubusercontent.com/45502788/71154320-3b06ad00-2276-11ea-9075-2d93c65be654.png">

附上：
`POST /ocr/captcha HTTP/1.1
Host: api.3023data.com
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
key: db98a53a73ec2b4eb600c83aaa5d26
Content-Length: 26

type=1001&length=&image=
`

**Comment by c0ny1** [comment]
该问题在此处（165e63df03891ce29448a837365225ebb40f88eb）已解决，请取最新源码。

![image](https://user-images.githubusercontent.com/15975792/71179221-b41ff780-22aa-11ea-8780-fd2a617d7b31.png)

**Comment by c0ny1** [comment]
后续出现类似请求失败问题，可以看下`Request raw`发送的最终数据包，和burp `Request`模块发送的数据包是否相同来排查问题。

**Comment by 7x0** [comment]
多谢大佬
