### ISSUE TITLE
百度OCR识别间隔宽度不一致的验证码后会有空格

### ISSUE THREAD

**Issue by Asiasara** [c0ny1/captcha-killer#3]
## 一、运行环境
* 操作系统： kali2019.3
* JDK版本：1.8.1_131
* Burp版本：2.1.06

## 二、问题描述
![2019-12-27_11-22](https://user-images.githubusercontent.com/55936412/71499383-32782d00-289b-11ea-8a62-c83c0472a6bd.png)
![2019-12-27_11-24](https://user-images.githubusercontent.com/55936412/71499410-4f146500-289b-11ea-97c9-fddbe06f0412.png)
识别出来的验证码存在空格，在爆破时候就会提示验证码错误

**Comment by c0ny1** [comment]
首先该问题是百度接口识别的问题，不是插件处理的问题。

解决的方法是在Intruder模块中payload处理添加`captcha-killer`后，继续添加一个`Match/replace`

![image](https://user-images.githubusercontent.com/15975792/71500071-57ba6a80-289e-11ea-8cd3-93d60a5a37e9.png)

**Comment by Asiasara** [comment]
感谢
