### ISSUE TITLE
添加requests模版时重发的requests raw报文异常导致404

### ISSUE THREAD

**Issue by doge-dog** [c0ny1/captcha-killer#4]
![image](https://user-images.githubusercontent.com/26864512/77276300-40501980-6cf5-11ea-8008-30eca54a3428.png)
可以看到部分行少了最后一个字符。
![image](https://user-images.githubusercontent.com/26864512/77276338-5a89f780-6cf5-11ea-8376-70b1a0779bcb.png)

**Comment by c0ny1** [comment]
你使用的版本不是最新源码，这个问题已经解决。

**Comment by doge-dog** [comment]
我是直接git clone然后mvn package遇到的情况，点击发包到captcha面板然后识别会发包错误，直接重发是正常的

**Comment by c0ny1** [comment]
你说的直接重发具体是什么，收到复制数据包到模版面板么

**Comment by doge-dog** [comment]
通过post报文是可以正常发包获取到结果的。
![image](https://user-images.githubusercontent.com/26864512/77601885-f9f1f900-6f46-11ea-9fda-74ad95bc51b3.png)
点击发送到captcha面板。
![image](https://user-images.githubusercontent.com/26864512/77601957-30c80f00-6f47-11ea-805f-a265a3042f4e.png)
然后修改captchaData为如下：
![image](https://user-images.githubusercontent.com/26864512/77602017-52c19180-6f47-11ea-9878-424b831f9690.png)
点击识别，回显了404。
![image](https://user-images.githubusercontent.com/26864512/77602041-61a84400-6f47-11ea-85b5-c0993863c669.png)
经过测试，发现requst raw跟requst template的有些行相差一个字符，例如host，导致显示404.
![image](https://user-images.githubusercontent.com/26864512/77602129-987e5a00-6f47-11ea-8e3d-ad475fd26f1d.png)

**Comment by doge-dog** [comment]
经过测试，在存在字符被清除的行后面加多一个空格就可以正常了。
![image](https://user-images.githubusercontent.com/26864512/77602584-d0d26800-6f48-11ea-9392-3ce3e08c458e.png)

**Comment by c0ny1** [comment]
我这边一直是正常的，有点迷。你能发下你去敏的模版数据包么

**Comment by doge-dog** [comment]
POST /upload HTTP/1.1
Host: v2-api.jsdama.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Connection: close
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
Content-Length: 754 

{"softwareId":xxxxx,"softwareSecret":"xxxxx","username":"xxxxx","password":"xxxxx","captchaData":"<@BASE64><@IMG_RAW></@IMG_RAW></@BASE64>","captchaType":1001,"captchaMinLength":0,"captchaMaxLength":0,"workerTipsId":0}

**Comment by doge-dog** [comment]
```
POST /upload HTTP/1.1
Host: v2-api.jsdama.com 
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0 
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2 
Accept-Encoding: gzip, deflate 
Connection: close 
Upgrade-Insecure-Requests: 1 
Content-Type: application/x-www-form-urlencoded 
Content-Length: 754 

{"softwareId":xxxxx,"softwareSecret":"xxxxx","username":"xxxxx","password":"xxxxx","captchaData":"<@BASE64><@IMG_RAW></@IMG_RAW></@BASE64>","captchaType":1001,"captchaMinLength":0,"captchaMaxLength":0,"workerTipsId":0}
```

**Comment by c0ny1** [comment]
这个问题已在此处解决 f37ba434952d874ca604f8d1ff01a041e2e4aa7c 请移步realse下载最新版。

![image](https://user-images.githubusercontent.com/15975792/77661739-fea1c600-6fb5-11ea-9f18-18c645377043.png)
