### ISSUE TITLE
能否增加一个可自己关闭验证码图片显示的功能

### ISSUE THREAD

**Issue by cwkiller** [c0ny1/captcha-killer#5]
#### 一、需求描述
能否增加一个可自己关闭验证码图片显示的功能
![image](https://user-images.githubusercontent.com/19302055/78523398-3a812a80-7803-11ea-9b4e-148518a97a0f.png)
#### 二、该功能的意义
因为在爆破的时候burp将大量图片显示出来会很卡

**Comment by c0ny1** [comment]
卡的原因可能是在swing线程当中进行验证码显示操作了，添加一个后台线程应该就可以解决了，关闭显示是没有方法的办法。最近空了改进下。

**Comment by c0ny1** [comment]
长时间没有反馈，默认认为问题已解决。
