### ISSUE TITLE
[BUG] 使用多线程爆破会出现验证码大量错误的情况

### ISSUE THREAD

**Issue by cwkiller** [c0ny1/captcha-killer#6]
## 一、运行环境
* 操作系统： Windows7
* JDK版本：1.8.1_131
* Burp版本：1.7.131

## 二、问题描述

使用多线程爆破会出现验证码大量错误的情况
一个线程
![image](https://user-images.githubusercontent.com/19302055/78523962-0a3a8b80-7805-11ea-836e-3b702d9f390d.png)
只错一个
![image](https://user-images.githubusercontent.com/19302055/78523976-145c8a00-7805-11ea-96bf-f4537e478617.png)
10线程
![image](https://user-images.githubusercontent.com/19302055/78524024-3a822a00-7805-11ea-98a4-48f91a75ce3a.png)
大量验证码错误（长度为220）
![image](https://user-images.githubusercontent.com/19302055/78524032-44a42880-7805-11ea-8465-e9f5074f0f80.png)
可能是多线程验证码图片未加载完导致的

**Comment by c0ny1** [comment]
这个先去插件页面排查下，验证码图片和识别的结果是否对应得上，是否正确。

**Comment by cwkiller** [comment]
![image](https://user-images.githubusercontent.com/19302055/78524852-cdbc5f00-7807-11ea-988f-750bf7afc91e.png)

**Comment by c0ny1** [comment]
确实不能多线程，还没识别完成，验证码已经被另一个线程刷新改变了。

**Comment by c0ny1** [comment]
受限于Burp的插件机制（提供的接口比较少），目前只能单线程。已经在文档中添加注意事项（ fdd4e0607898943f2d83b300d18aee937c5faa4f ）
