### ISSUE TITLE
接口响应数据格式

### ISSUE THREAD

**Issue by uknowsec** [c0ny1/captcha-killer#8]
#### 一、需求描述
某些接口的接口响应数据格式不是固定的，数据结构属性顺序不固定，所以已有的几种匹配方式就失效了。
如下某接口返回数据格式其中两种：
```
{
    "data": {
        "captchaId": "20200520:000000000041662091123",
        "recognition": "YBKR"
    },
    "message": "",
    "code": 0
}
```
```
{"code":0,"data":{"recognition":"DMXZ","captchaId":"20200520:000000000041663755582"},"message":""}
```

#### 二、建议
建议用json库对返回接口进行解析，然后获取特定key值的value，准确匹配到接口返回结果。
如上解析json数据获取recognition的值。

可添加一种匹配方法，直接填入验证码的key值直接去获取他的value。一劳永逸~

**Comment by c0ny1** [comment]
1. 按理说正则应该是可以匹配的，比如你提供的例子设置匹配规则为`"recognition":"(.*?)",`
2. 关于添加son解析，在后续版本会添加json和xml数据解析匹配

**Comment by c0ny1** [comment]
最新源码已经添加json方式匹配结果（ b22379d8ee040878859a60a0c3c89acab365be4d ）
![image](https://user-images.githubusercontent.com/15975792/82640557-67679080-9c3d-11ea-87f8-76482ed9cf17.png)

**Comment by uknowsec** [comment]
> 最新源码已经添加json方式匹配结果（ [b22379d](https://github.com/c0ny1/captcha-killer/commit/b22379d8ee040878859a60a0c3c89acab365be4d) ）
> ![image](https://user-images.githubusercontent.com/15975792/82640557-67679080-9c3d-11ea-87f8-76482ed9cf17.png)

大佬太强了 效率的一批~
